# Generated by Django 4.2.25 on 2026-05-22 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo (optional)', null=True, upload_to=users.models.user_avatar_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.CreateModel(
            name='HealthVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_type', models.CharField(choices=[('bp_systolic', 'Blood Pressure (Systolic)'), ('bp_diastolic', 'Blood Pressure (Diastolic)'), ('glucose', 'Blood Glucose (mg/dL)'), ('weight', 'Weight (kg)'), ('heart_rate', 'Heart Rate (bpm)'), ('oxygen_sat', 'Oxygen Saturation (%)'), ('temperature', 'Body Temperature (°C)')], max_length=30)),
                ('value', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodDonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_at', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('recipient_note', models.CharField(blank=True, max_length=200)),
                ('units', models.FloatField(default=1.0, help_text='Units of blood donated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-donated_at'],
            },
        ),
    ]
