# Generated by Django 4.2.25 on 2025-10-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('upazila', models.CharField(max_length=100)),
                ('professional', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('degree', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['division', 'district', 'provider'],
            },
        ),
    ]
